name: neon
description: "Flutter Mastodon client"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  dio: ^5.9.1
  get_it: ^9.2.1
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  skeletonizer: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/adaptive.png
    - assets/splash.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: JetBrains_Mono
      fonts:
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Light.ttf
          weight: 300
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani/Rajdhani-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rajdhani/Rajdhani-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rajdhani/Rajdhani-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rajdhani/Rajdhani-Light.ttf
          weight: 300
